### ISSUE TITLE
Some way to export settings within the project?

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/unittestgenerator#12]
Hi, so now the extension can be configured, it works great.

However each team member would have to configure it to match the project style. It would be amazing if the config could be exported, so I could add it to the .git repository, and then anyone using the project would automatically get the same settings

I would like to see a `.unitverse` file which can be saved to the repository

**Comment by mattwhitfield** [comment]
Have a look at the 'Setting options per-solution' section on https://github.com/mattwhitfield/unittestgenerator/blob/master/README.md - this should be able to achieve what you want.

I'm not sure if you hadn't seen that, or if you're asking for something else? Either way, feedback would be good as it probably points to an issue with either a missing feature or the documentation 👍

**Comment by CoenraadS** [comment]
Oh indeed I didn't really check the documentation first 🤦

But I think having an 'export settings' button in the options would make it easier and more discoverable

**Comment by mattwhitfield** [comment]
Ok, leave it with me. I know there is a way that you can put custom controls on those options pages, but I haven't really dug into it. There should be a way to add another options page 'export' which basically has some description and lets you save off a config that represents the currently configured settings.

Thanks!

**Comment by mattwhitfield** [comment]
0.79 is out now and that adds the facility to save the current settings in the options 👍
