### ISSUE TITLE
Feature Request: Support test generation for items marked with "internal" access.

### ISSUE THREAD

**Issue by eobeda** [mattwhitfield/unittestgenerator#16]
I'd like to suggest a new feature:
Adding an option to define the scope of the methods/etc. selected for test generation.

- public only
- public and internal
- [public, internal and private]  <-- maybe

I believe, based on my use, that only public items are selected for test generation. I also know that not everyone believes that non-public methods, should be included in units tests. 

Adding the feature doesn't limit these beliefs, but does open up the use of Unitverse extension to more user scenarios.

Thanks for your consideration.

**Comment by mattwhitfield** [comment]
That's a good shout - I'll probably add an option 'Emit tests for internal members'. I probably wouldn't do private - because calling those would require reflection, which probably isn't something all that useful. But I'll definitely add the internal bit 👍

**Comment by mattwhitfield** [comment]
Implemented in 0.81 - let me know if that works for you 👍

**Comment by mattwhitfield** [comment]
Oh - forgot to say - it's disabled by default (to keep behaviour the same for existing installs)

**Comment by eobeda** [comment]
Perfect 👍 

Tried it out this morning. Works as requested.

Thanks for the super fast turnaround.
Thanks for your efforts on Unitverse as well.

-- Ed
