### ISSUE TITLE
Variable naming options

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/unittestgenerator#3]
Hey, love the extension!

One thing I would like to see is an option to name variables without the leading underscore.

And another would for the testClass to be called `sut` (System Under Test)

**Comment by mattwhitfield** [comment]
Good suggestions - I'll add those 👍

**Comment by mattwhitfield** [comment]
@CoenraadS - version 0.75 is out now that adds support for customizing these names. If it doesn't match what you expected then please do let me know 👍

**Comment by mattwhitfield** [comment]
Version 0.77 is out now that fixes the support for customizable '_testClass' field naming when generating tests for abstract classes 👍

**Comment by CoenraadS** [comment]
Great 😃 I'll be sure to check it out after my holidays ☺️

**Comment by mattwhitfield** [comment]
Have a good one!

**Comment by CoenraadS** [comment]
Just tried it, works great!

**Comment by mattwhitfield** [comment]
Thanks for the feedback, appreciate it!
