### ISSUE TITLE
Add support for record types

### ISSUE THREAD

**Issue by mattwhitfield** [mattwhitfield/unittestgenerator#35]
It would be good to generate tests for record types

**Comment by 304NotModified** [comment]
Im excited to test this extension, but I really need record support. So would be great if added:)

**Comment by mattwhitfield** [comment]
Ok, well I have an initial cut of the record type support - I didn't do the equality checks yet - I think if I do that I would emit general tests for anything that implements `IEquatable<T>`. There are examples of the record type generation at https://unitverse.readthedocs.io/en/latest/examples/RecordTypeInitProperties/ and https://unitverse.readthedocs.io/en/latest/examples/RecordTypesPrimaryConstructor/. I'd be interested to hear your feedback.

In fact, that is the case in general - if there's anything you think should be supported / configurable etc then please do open an issue 👍

**Comment by mattwhitfield** [comment]
Sample for IEquatable<T> output is https://unitverse.readthedocs.io/en/latest/examples/IEquatableTests/ - specifically the `ImplementsIEquatable_Complex` method

**Comment by mattwhitfield** [comment]
Closing this now as I think everything is covered 👍

**Comment by 304NotModified** [comment]
--> https://github.com/mattwhitfield/unittestgenerator/issues/55
