### ISSUE TITLE
Option for namespace to be declared after using statements

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/unittestgenerator#4]
Minor polish issue, would be great is this could be configurable

**Comment by mattwhitfield** [comment]
Good suggestion - will add 👍

**Comment by mattwhitfield** [comment]
@CoenraadS - version 0.76 is out now - that adds an option to generate the usings outside the namespace 🎉

**Comment by CoenraadS** [comment]
Just tried it, works great!

**Comment by mattwhitfield** [comment]
Thanks for the feedback, appreciate it!
