### ISSUE TITLE
Option to disable null tests

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/unittestgenerator#42]
Hi again :) Really enjoying this extension so far

I would like to see an option to disable the auto generated tests which check the behavior with null types. Our code base never has any nulls, so we also don't guard against them, and also are not interested in testing for them

Also an option to disable the CanConstruct test

**Comment by mattwhitfield** [comment]
Glad you're liking it :) 

It *sounds* like we need a way to turn off specific strategies. So for each different type of test, you could choose if it was emitted or not...

For the tests that test constructor parameters, would you still see value in the empty string and whitespace tests? Or would you just get rid of them entirely?

**Comment by CoenraadS** [comment]
We do offensive programming and our code isn't littered with these kind checks, so for me I'm always deleting these tests.

**Comment by mattwhitfield** [comment]
Ok thanks both... I think being able to control it 'per strategy' would probably work then... Shouldn't be a big deal although the refactor will touch a bunch of files.

**Comment by mattwhitfield** [comment]
Implemented in 0.95 👍 You can now go to Tools -> Options -> Unitverse -> Strategy Options to control which types of tests get generated.

There is an issue with it, to do with emitting derived classes for protected members. I opened a separate issue for it (#46) because it needs a bit of care to get right.

Let me know if that works for you.

**Comment by mattwhitfield** [comment]
Closing this now - @CoenraadS - if it doesn't work for you please feel free to open another issue 👍
