### ISSUE TITLE
usings above namespace

### ISSUE THREAD

**Issue by 304NotModified** [mattwhitfield/unittestgenerator#43]
Maybe this is really opionated,

But the `using` in the default class template of Visual studio is above the `namespace`

Current result:

```c#
namespace MyNameSpace
{
    using System;
    using Xunit;
    using FluentAssertions;

    public class MyClassTests
    {
```

expected/desired:

```c#
using System;
using Xunit;
using FluentAssertions;

namespace MyNameSpace
{
    public class MyClassTests
    {
```

For example, the new class template in VS2022 generates:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyNameSpace
{
    internal class Class1
    {
    }
}
```

**Comment by mattwhitfield** [comment]
Have a look at https://github.com/mattwhitfield/unittestgenerator/blob/master/src/Unitverse/Options/GenerationOptions.cs - EmitUsingsOutsideNamespace - should show up in Tools -> Options -> Unitverse 👍

**Comment by 304NotModified** [comment]
Ow great! Thanks!
