### ISSUE TITLE
[Feature] Support Moq.AutoMock

### ISSUE THREAD

**Issue by 304NotModified** [mattwhitfield/unittestgenerator#44]
Would be cool if this generator detects and supports [Moq.AutoMock](https://www.nuget.org/packages/Moq.AutoMock)

e.g.

```c#
var mocker = new AutoMocker();
_logger = mocker.GetMock<ILogger<MyClass>>();
_sut = mocker.CreateInstance<MyClass>();
```

**Comment by mattwhitfield** [comment]
Interesting... I will have to give that one some thought as to how it would plug in... Presumably you'd still want constructor tests for null guards, but then `_sut` or `_testClass` or whatever you've called it came from AutoMocker... ?

**Comment by 304NotModified** [comment]
The difference is that the instance (and all the mocks) are created by automoq. This is more agile to changes,  e.g. adding or changing parameters of a constructor of the test class

(And yes, i name the test class l, [sut](https://en.m.wikipedia.org/wiki/System_under_test))

**Comment by mattwhitfield** [comment]
👍

With unitverse I haven't really worried about that too much - you just hold shift, right click on the constructor method and click 'Regenerate tests for all constructors' and it mostly just sorts you out.

But leave it with me - I think I should be able to add support for it.

**Comment by mattwhitfield** [comment]
@304NotModified - sorry - some questions...

If you have a normal sort of 'model' class - so say takes a string and an int as params and has those as gettable properties - presumably you wouldn't create that class with AutoMocker.CreateInstance? 

And what would be the desired outcome for a class that took a mixture of interfaces and value types as constructor params?

I just haven't used Moq.AutoMock so wanted to ask your wisdom 👍

**Comment by 304NotModified** [comment]
> If you have a normal sort of 'model' class - so say takes a string and an int as constructor params and has those as gettable properties - presumably you wouldn't create that class with AutoMocker.CreateInstance?

Thats correct. AutoMocker is only useful if we need mocks (of services)



> And what would be the desired outcome for a class that took a mixture of interfaces and value types as constructor params?

Have to think about that. Im not sure its possible with automock, but its also a bad design IMO 😅

**Comment by mattwhitfield** [comment]
> Im not sure its possible with automock, but its also a bad design IMO 😅
Unfortunately, both good and bad designers are free to use Unitverse 🤣

Seriously though, I'll wait to see what you think. It could be that in that case we just emit 'normal' mocks. That way, if you avoid that pattern, then no problem...

**Comment by mattwhitfield** [comment]
So I think I have got this sorted - example at https://github.com/mattwhitfield/unittestgenerator/blob/feature/MoqAutoMock/docs/examples/FrameworksMsTestMoqAutoMock.md

It will use AutoMocker in the case that all the parameters to the 'default constructor' are interfaces. The default constructor is the constructor that has the highest number of parameters.

**Comment by mattwhitfield** [comment]
Supported in 0.100 - and example doc is at https://unitverse.readthedocs.io/en/latest/examples/FrameworksMsTestMoqAutoMock/ 👍

**Comment by 304NotModified** [comment]
cool!
